

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Phoenix Test Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule: # Set the Cron for Midnight IST --- UTC
    - cron: "30 18 * * *"
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        type: choice
        options: [test,uat,dev]
        default: test
        required: true
      suiteXmlFile:
        description: "TestNG xml File"
        type: choice
        options: [testng.xml,smoke.xml,regression.xml]
        default: testng.xml
        required: true
      

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Execute Test Automation Framework
      run: |
        mvn clean test \
         -DsuiteXmlFile="${{ github.event.inputs.suiteXmlFile || 'testng.xml' }}" \
         -Denv="${{ github.event.inputs.env || 'test' }}"

    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v5.0.0
      with:
        name: Surefire Report
        path: target/surefire-reports
        retention-days: 10
      
      

   


   
